# Site settings
# Some stories needs to be wrote, some tale told, some adventures lived.
title: Martial - Dev
presentation: >
	Merci á vous, de me rejoindre sur ce blog, où on parlera de "code", "design pattern",
	de "best practice" et de quelques outils essentiel à un developpeur moderne.
email: martialkonvi@gmail.com
description: >
  Welcome to my tale about great apps development and software engineering.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://martialkonvi.github.io" # the base hostname & protocol for your site
twitter_username: martialkonvi
github_username:  martialkonvi

# Build settings
markdown: kramdown

paginate: 4

author: Martial Konvi

gems: [jekyll-paginate]
